- id: '1773527132508'
  alias: Living Room Media Wall Keypad Buttons
  description: ''
  use_blueprint:
    path: bengber/lutron-sunnata-keypad-click-long-click-double-click.yaml
    input:
      sunnata_keypad: c961ebf447db2fbfe64d17efa4237468
      button_3_single_click:
      - action: scene.turn_on
        metadata: {}
        target:
          entity_id: scene.movie_time
        data:
          transition: 3
- id: '1773625583313'
  alias: Dining Rear Hall Entry Keypad Buttons
  description: ''
  use_blueprint:
    path: bengber/lutron-sunnata-keypad-click-long-click-double-click.yaml
    input:
      sunnata_keypad: aa916d18a22b3513ea789e3130c81bbd
      button_4_single_click:
      - action: scene.turn_on
        metadata: {}
        target:
          entity_id: scene.bed_time
        data:
          transition: 5
