- name: Movie Time
  entities:
    light.sofa_table_left:
      state: "on"
      brightness: 31
      color_temp_kelvin: 2200
      transition: 3
    light.sofa_table_right:
      state: "on"
      brightness: 31
      color_temp_kelvin: 2200
      transition: 3
    light.floor_lamp_center:
      state: "on"
      brightness: 13
      color_temp_kelvin: 2200
      transition: 3
    light.floor_lamp_left:
      state: "on"
      brightness: 13
      color_temp_kelvin: 2200
      transition: 3
    light.floor_lamp_right:
      state: "on"
      brightness: 13
      color_temp_kelvin: 2200
      transition: 3
- name: Bed Time
  entities:
    light.sofa_table_left:
      state: "off"
    light.sofa_table_right:
      state: "off"
    light.floor_lamp_center:
      state: "off"
    light.floor_lamp_left:
      state: "off"
    light.floor_lamp_right:
      state: "off"
