- binary_sensor:
    - name: "Kitchen Lights On"
      unique_id: "kitchen_lights_on"
      device_class: light
      state: >
        {{ expand(area_entities('kitchen'))
           | selectattr('domain', 'eq', 'light')
           | selectattr('state', 'eq', 'on')
           | list | count > 0
           or
           expand(label_entities('light_switch')
           | select('in', area_entities('kitchen')) | list)
           | selectattr('state', 'eq', 'on')
           | list | count > 0 }}

    - name: "Living Area Lights On"
      unique_id: "living_area_lights_on"
      device_class: light
      state: >
        {{ expand(area_entities('living_area'))
           | selectattr('domain', 'eq', 'light')
           | selectattr('state', 'eq', 'on')
           | list | count > 0
           or
           expand(label_entities('light_switch')
           | select('in', area_entities('living_area')) | list)
           | selectattr('state', 'eq', 'on')
           | list | count > 0 }}

    - name: "Master Bedroom Lights On"
      unique_id: "master_bedroom_lights_on"
      device_class: light
      state: >
        {{ expand(area_entities('master_bedroom'))
           | selectattr('domain', 'eq', 'light')
           | selectattr('state', 'eq', 'on')
           | list | count > 0
           or
           expand(label_entities('light_switch')
           | select('in', area_entities('master_bedroom')) | list)
           | selectattr('state', 'eq', 'on')
           | list | count > 0 }}

    - name: "Master Bath Lights On"
      unique_id: "master_bath_lights_on"
      device_class: light
      state: >
        {{ expand(area_entities('master_bath'))
           | selectattr('domain', 'eq', 'light')
           | selectattr('state', 'eq', 'on')
           | list | count > 0
           or
           expand(label_entities('light_switch')
           | select('in', area_entities('master_bath')) | list)
           | selectattr('state', 'eq', 'on')
           | list | count > 0 }}

    - name: "Master Suite Lights On"
      unique_id: "master_suite_lights_on"
      device_class: light
      state: >
        {{ is_state('binary_sensor.master_bedroom_lights_on', 'on')
          or is_state('binary_sensor.master_bath_lights_on', 'on') }}

    # - name: "Guest Bedroom Lights On"
    #   unique_id: "guest_bedroom_lights_on"
    #   device_class: light
    #   state: >
    #     {{ expand(area_entities('guest_bedroom'))
    #        | selectattr('domain', 'eq', 'light')
    #        | selectattr('state', 'eq', 'on')
    #        | list | count > 0
    #        or
    #        expand(label_entities('light_switch')
    #        | select('in', area_entities('guest_bedroom')) | list)
    #        | selectattr('state', 'eq', 'on')
    #        | list | count > 0 }}

    # - name: "Guest Bath Lights On"
    #   unique_id: "guest_bath_lights_on"
    #   device_class: light
    #   state: >
    #     {{ expand(area_entities('guest_bath'))
    #        | selectattr('domain', 'eq', 'light')
    #        | selectattr('state', 'eq', 'on')
    #        | list | count > 0
    #        or
    #        expand(label_entities('light_switch')
    #        | select('in', area_entities('guest_bath')) | list)
    #        | selectattr('state', 'eq', 'on')
    #        | list | count > 0 }}

    - name: "Office Lights On"
      unique_id: "office_lights_on"
      device_class: light
      state: >
        {{ expand(area_entities('office'))
           | selectattr('domain', 'eq', 'light')
           | selectattr('state', 'eq', 'on')
           | list | count > 0
           or
           expand(label_entities('light_switch')
           | select('in', area_entities('office')) | list)
           | selectattr('state', 'eq', 'on')
           | list | count > 0 }}

    - name: "Mud Room Lights On"
      unique_id: "mud_room_lights_on"
      device_class: light
      state: >
        {{ expand(area_entities('mud_room'))
           | selectattr('domain', 'eq', 'light')
           | selectattr('state', 'eq', 'on')
           | list | count > 0
           or
           expand(label_entities('light_switch')
           | select('in', area_entities('mud_room')) | list)
           | selectattr('state', 'eq', 'on')
           | list | count > 0 }}

    - name: "Laundry Room Lights On"
      unique_id: "laundry_room_lights_on"
      device_class: light
      state: >
        {{ expand(area_entities('laundry_room'))
           | selectattr('domain', 'eq', 'light')
           | selectattr('state', 'eq', 'on')
           | list | count > 0
           or
           expand(label_entities('light_switch')
           | select('in', area_entities('laundry_room')) | list)
           | selectattr('state', 'eq', 'on')
           | list | count > 0 }}

    - name: "Laundry/Mud Room Lights On"
      unique_id: "laundry_mud_room_lights_on"
      device_class: light
      state: >
        {{ is_state('binary_sensor.laundry_room_lights_on', 'on')
          or is_state('binary_sensor.mud_room_lights_on', 'on') }}

    - name: "Powder Room Lights On"
      unique_id: "powder_room_lights_on"
      device_class: light
      state: >
        {{ expand(area_entities('powder_room'))
           | selectattr('domain', 'eq', 'light')
           | selectattr('state', 'eq', 'on')
           | list | count > 0
           or
           expand(label_entities('light_switch')
           | select('in', area_entities('powder_room')) | list)
           | selectattr('state', 'eq', 'on')
           | list | count > 0 }}

    - name: "Patio Lights On"
      unique_id: "patio_lights_on"
      device_class: light
      state: >
        {{ expand(area_entities('patio'))
           | selectattr('domain', 'eq', 'light')
           | selectattr('state', 'eq', 'on')
           | list | count > 0
           or
           expand(label_entities('light_switch')
           | select('in', area_entities('patio')) | list)
           | selectattr('state', 'eq', 'on')
           | list | count > 0 }}

    - name: "Exterior Lights On"
      unique_id: "exterior_lights_on"
      device_class: light
      state: >
        {{ expand(area_entities('exterior'))
           | selectattr('domain', 'eq', 'light')
           | selectattr('state', 'eq', 'on')
           | list | count > 0
           or
           expand(label_entities('light_switch')
           | select('in', area_entities('exterior')) | list)
           | selectattr('state', 'eq', 'on')
           | list | count > 0 }}

- sensor:
    - name: "Lights On Counter"
      unique_id: "lights_on_counter"
      icon: mdi:lightbulb-group
      state: >
        {{
          (
            states.light
            | rejectattr('attributes.entity_id', 'defined')
            | rejectattr('entity_id', 'in', expand(label_entities('light_fixture_member')) | map(attribute='entity_id') | list)
            | rejectattr('entity_id', 'in', expand(label_entities('light_fixture_group')) | map(attribute='entity_id') | list)
            | selectattr('state', 'eq', 'on')
            | list | count
          )
          +
          (
            expand(label_entities('light_fixture_group'))
            | selectattr('state', 'eq', 'on')
            | list | count
          )
          +
          (
            expand(label_entities('light_switch'))
            | selectattr('state', 'eq', 'on')
            | list | count
          )
        }}

    - name: "Fans On Counter"
      unique_id: "fans_on_counter"
      icon: mdi:fan
      state: >
        {{ expand(label_entities('fan_switch'))
           | selectattr('state', 'eq', 'on')
           | list | count }}

    - name: "Ceiling Fans On Counter"
      unique_id: "ceiling_fans_on_counter"
      icon: mdi:ceiling-fan
      state: >
        {{ expand(label_entities('ceiling_fan'))
           | selectattr('state', 'eq', 'on')
           | list | count }}

- sensor:
    - name: "Workshop HVAC Action"
      unique_id: "workshop_hvac_action"
      icon: mdi:air-conditioner
      state: "{{ state_attr('climate.workshop', 'hvac_action') }}"
